In [1]:
import os, sys
import zipfile
import pandas as pd

In [16]:
cwd = os.getcwd()
raw_path = os.path.join(os.path.dirname(cwd),'data','raw','FOB')
zip_files = [f for f in os.listdir(raw_path) if os.path.splitext(f)[1] == '.zip']
display(zip_files)

['XPAR_SHARES_F1_20231002.csv.zip']

In [25]:
for f in zip_files:
    if os.path.splitext(f)[0] not in os.listdir(raw_path):
        with zipfile.ZipFile(os.path.join(raw_path, f), 'r') as zip_ref:
            zip_ref.extractall(raw_path)
        
    df = pd.read_csv(os.path.join(raw_path, os.path.splitext(f)[0]), usecols=['isin'])
    
    #display(df.tolist())

In [33]:
display(df['isin'].unique()[0])
isin = df['isin'].unique()[0]

'FR0000045072'

In [35]:
chunks = []
for chunk in pd.read_csv(os.path.join(raw_path, os.path.splitext(f)[0]), 
                         header=0, 
                         low_memory=False, 
                         chunksize=10000, 
                         usecols=['isin',
                                   'event_date',
                                   'event_time_cet',
                                   'event_id',
                                   'order_id',
                                   'order_event_type',
                                   'order_side',
                                   'order_price',
                                   'order_size',
                                   'order_type',
                                   'time_in_force']):
    chunk = chunk[chunk['isin'] == isin]

    chunk['event_time_cet'] = pd.to_datetime(chunk['event_date'] + ' ' + chunk['event_time_cet'])
    chunk = chunk.drop(columns=['event_date'])
    chunks.append(chunk)
    
DF = pd.concat(chunks).sort_values(by=['event_time_cet'])

In [39]:
display(DF.reset_index(drop=True))
display(DF)

,isin,event_time_cet,event_id,order_id,order_event_type,order_side,order_price,order_size,order_type,time_in_force
0,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,16862367,Reload,Sell,16.50,500.0,Limit,0
1,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4913811770490,Reload,Sell,13.88,36.0,Limit,0
2,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4844437982335,Reload,Sell,11.90,100.0,Limit,0
3,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4840109460638,Reload,Sell,11.98,892.0,Limit,0
4,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4838532402292,Reload,Sell,12.00,25.0,Limit,0
...,...,...,...,...,...,...,...,...,...,...
679969,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,2197900464,Cancel,Sell,12.18,0.0,Limit,0
679970,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,21122600112,Cancel,Sell,12.19,0.0,Limit,0
679971,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,1219636579504,Cancel,Sell,12.19,0.0,Limit,0
679972,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,1124158640,Cancel,Sell,12.20,0.0,Limit,0
679973,FR0000045072,2023-10-02 17:50:00.417817476,75310254375578710,37950147760,Cancel,Buy,7.09,0.0,Limit,0

,isin,event_time_cet,event_id,order_id,order_event_type,order_side,order_price,order_size,order_type,time_in_force
0,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,16862367,Reload,Sell,16.50,500.0,Limit,0
3301,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4913811770490,Reload,Sell,13.88,36.0,Limit,0
3300,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4844437982335,Reload,Sell,11.90,100.0,Limit,0
3299,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4840109460638,Reload,Sell,11.98,892.0,Limit,0
3298,FR0000045072,2023-10-02 03:01:12.559510032,363384194933456904,4838532402292,Reload,Sell,12.00,25.0,Limit,0
...,...,...,...,...,...,...,...,...,...,...
679579,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,2197900464,Cancel,Sell,12.18,0.0,Limit,0
679580,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,21122600112,Cancel,Sell,12.19,0.0,Limit,0
679581,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,1219636579504,Cancel,Sell,12.19,0.0,Limit,0
679583,FR0000045072,2023-10-02 17:40:00.020208215,435441788971385872,1124158640,Cancel,Sell,12.20,0.0,Limit,0
679973,FR0000045072,2023-10-02 17:50:00.417817476,75310254375578710,37950147760,Cancel,Buy,7.09,0.0,Limit,0

In [45]:
display(DF[DF['order_event_type'] == 'Modify'])
display(DF[DF['order_event_type'] == 'Cancel'][5000:6000])

,isin,event_time_cet,event_id,order_id,order_event_type,order_side,order_price,order_size,order_type,time_in_force
6410,FR0000045072,2023-10-02 08:33:49.044517384,75309713209688530,10804612272,Modify,Sell,12.964,22.0,Limit,0
6415,FR0000045072,2023-10-02 08:35:57.697602212,75310821311254335,8992672944,Modify,Buy,11.480,5.0,Limit,0
6417,FR0000045072,2023-10-02 08:36:47.632725357,75310821311254338,1426148528,Modify,Buy,11.492,5.0,Limit,0
6420,FR0000045072,2023-10-02 08:37:14.794703517,75310821311254339,8992672944,Modify,Buy,11.542,5.0,Limit,0
6534,FR0000045072,2023-10-02 08:59:06.938862778,75306324480491541,26910739632,Modify,Buy,11.740,2346.0,Limit,0
...,...,...,...,...,...,...,...,...,...,...
677608,FR0000045072,2023-10-02 17:35:09.744600227,75308416129571319,5243953826992,Modify,Sell,11.540,868.0,Limit,0
677612,FR0000045072,2023-10-02 17:35:12.812285360,75270229575338464,5248953437360,Modify,Sell,10.960,6751.0,Limit,Valid for Closing
679340,FR0000045072,2023-10-02 17:36:43.719651490,75308854216229385,5245950315696,Modify,Sell,11.536,4631.0,Limit,0
679341,FR0000045072,2023-10-02 17:36:45.791248138,75308854216229389,5245950315696,Modify,Sell,11.536,4631.0,Limit,0
679342,FR0000045072,2023-10-02 17:36:48.119474665,75308854216229393,5245950315696,Modify,Sell,11.536,4631.0,Limit,0

,isin,event_time_cet,event_id,order_id,order_event_type,order_side,order_price,order_size,order_type,time_in_force
14426,FR0000045072,2023-10-02 09:03:53.145669013,75309756159361362,80329395376,Cancel,Sell,11.724,0.0,Limit,0
14427,FR0000045072,2023-10-02 09:03:53.145682003,75269821553444287,83768724656,Cancel,Buy,11.696,0.0,Limit,0
14428,FR0000045072,2023-10-02 09:03:53.168269829,75270263935077438,85496777904,Cancel,Sell,11.728,0.0,Limit,0
14431,FR0000045072,2023-10-02 09:03:53.193491037,75309502756315094,84909575344,Cancel,Buy,11.706,0.0,Limit,0
14432,FR0000045072,2023-10-02 09:03:53.200026590,75308364589959906,84993461424,Cancel,Buy,11.672,0.0,Limit,0
...,...,...,...,...,...,...,...,...,...,...
16461,FR0000045072,2023-10-02 09:05:17.440545964,75310361749765518,104723467440,Cancel,Sell,11.708,0.0,Limit,0
16463,FR0000045072,2023-10-02 09:05:17.442597117,75310366044732769,104740244656,Cancel,Buy,11.704,0.0,Limit,0
16465,FR0000045072,2023-10-02 09:05:17.490288286,75310366044732772,104757021872,Cancel,Buy,11.706,0.0,Limit,0
16468,FR0000045072,2023-10-02 09:05:17.493308559,75310361749765523,104790576304,Cancel,Buy,11.704,0.0,Limit,0
16470,FR0000045072,2023-10-02 09:05:17.501424091,75310361749765526,104773799088,Cancel,Sell,11.708,0.0,Limit,0