In [1]:
import os, sys
import pandas as pd
from filelock import FileLock
import numpy as np

In [2]:
cwd = os.getcwd()
raw_path = os.path.join(os.path.dirname(cwd),'data','raw','FOB')
zip_files = [f for f in os.listdir(raw_path) if os.path.splitext(f)[1] == '.zip']
display(zip_files)

['XPAR_SHARES_F1_20231002.csv.zip']

In [30]:
if 'FOB_DB.csv' in os.listdir(cwd):
    display('ok')
    
else:
    sys.exit('FOB_DB.csv does not exist.')
    
df = pd.read_csv(os.path.join(cwd, 'FOB_DB.csv'), index_col=0)
display(df)

'ok'

Empty DataFrame
Columns: [file, isin, state, allocate]
Index: []

In [34]:
if df.empty:
    ls = pd.read_csv(os.path.join(raw_path, os.path.splitext(zip_files[0])[0]), usecols=['isin'])['isin'].unique().tolist()
    df['isin'] = ls
    df[['file','state','allocate']] = zip_files[0],'Pending',None
    display(df)

                               file          isin    state allocate
0   XPAR_SHARES_F1_20231002.csv.zip  FR0000045072  Pending     None
1   XPAR_SHARES_F1_20231002.csv.zip  FR0000051807  Pending     None
2   XPAR_SHARES_F1_20231002.csv.zip  FR0000052292  Pending     None
3   XPAR_SHARES_F1_20231002.csv.zip  FR0000120073  Pending     None
4   XPAR_SHARES_F1_20231002.csv.zip  FR0000120172  Pending     None
5   XPAR_SHARES_F1_20231002.csv.zip  FR0000120503  Pending     None
6   XPAR_SHARES_F1_20231002.csv.zip  FR0000120628  Pending     None
7   XPAR_SHARES_F1_20231002.csv.zip  FR0000120644  Pending     None
8   XPAR_SHARES_F1_20231002.csv.zip  FR0000121014  Pending     None
9   XPAR_SHARES_F1_20231002.csv.zip  FR0000121667  Pending     None
10  XPAR_SHARES_F1_20231002.csv.zip  FR0000125338  Pending     None
11  XPAR_SHARES_F1_20231002.csv.zip  FR0000131104  Pending     None
12  XPAR_SHARES_F1_20231002.csv.zip  FR0000133308  Pending     None
13  XPAR_SHARES_F1_20231002.csv.zip  FR0010208488  Pending     None
14  XPAR_SHARES_F1_20231002.csv.zip  FR0010220475  Pending     None
15  XPAR_SHARES_F1_20231002.csv.zip  FR0010307819  Pending     None
16  XPAR_SHARES_F1_20231002.csv.zip  FR0013326246  Pending     None
17  XPAR_SHARES_F1_20231002.csv.zip  FR0014000MR3  Pending     None
18  XPAR_SHARES_F1_20231002.csv.zip  FR001400AJ45  Pending     None
19  XPAR_SHARES_F1_20231002.csv.zip  NL0000235190  Pending     None

In [35]:
display(df)

                               file          isin    state allocate
0   XPAR_SHARES_F1_20231002.csv.zip  FR0000045072  Pending     None
1   XPAR_SHARES_F1_20231002.csv.zip  FR0000051807  Pending     None
2   XPAR_SHARES_F1_20231002.csv.zip  FR0000052292  Pending     None
3   XPAR_SHARES_F1_20231002.csv.zip  FR0000120073  Pending     None
4   XPAR_SHARES_F1_20231002.csv.zip  FR0000120172  Pending     None
5   XPAR_SHARES_F1_20231002.csv.zip  FR0000120503  Pending     None
6   XPAR_SHARES_F1_20231002.csv.zip  FR0000120628  Pending     None
7   XPAR_SHARES_F1_20231002.csv.zip  FR0000120644  Pending     None
8   XPAR_SHARES_F1_20231002.csv.zip  FR0000121014  Pending     None
9   XPAR_SHARES_F1_20231002.csv.zip  FR0000121667  Pending     None
10  XPAR_SHARES_F1_20231002.csv.zip  FR0000125338  Pending     None
11  XPAR_SHARES_F1_20231002.csv.zip  FR0000131104  Pending     None
12  XPAR_SHARES_F1_20231002.csv.zip  FR0000133308  Pending     None
13  XPAR_SHARES_F1_20231002.csv.zip  FR0010208488  Pending     None
14  XPAR_SHARES_F1_20231002.csv.zip  FR0010220475  Pending     None
15  XPAR_SHARES_F1_20231002.csv.zip  FR0010307819  Pending     None
16  XPAR_SHARES_F1_20231002.csv.zip  FR0013326246  Pending     None
17  XPAR_SHARES_F1_20231002.csv.zip  FR0014000MR3  Pending     None
18  XPAR_SHARES_F1_20231002.csv.zip  FR001400AJ45  Pending     None
19  XPAR_SHARES_F1_20231002.csv.zip  NL0000235190  Pending     None

In [46]:
test = df.copy()
test.loc[2, ['state','allocate']] = 'In progress', 1
display(test)

                               file          isin        state allocate
0   XPAR_SHARES_F1_20231002.csv.zip  FR0000045072      Pending     None
1   XPAR_SHARES_F1_20231002.csv.zip  FR0000051807      Pending     None
2   XPAR_SHARES_F1_20231002.csv.zip  FR0000052292  In progress        1
3   XPAR_SHARES_F1_20231002.csv.zip  FR0000120073      Pending     None
4   XPAR_SHARES_F1_20231002.csv.zip  FR0000120172      Pending     None
5   XPAR_SHARES_F1_20231002.csv.zip  FR0000120503      Pending     None
6   XPAR_SHARES_F1_20231002.csv.zip  FR0000120628      Pending     None
7   XPAR_SHARES_F1_20231002.csv.zip  FR0000120644      Pending     None
8   XPAR_SHARES_F1_20231002.csv.zip  FR0000121014      Pending     None
9   XPAR_SHARES_F1_20231002.csv.zip  FR0000121667      Pending     None
10  XPAR_SHARES_F1_20231002.csv.zip  FR0000125338      Pending     None
11  XPAR_SHARES_F1_20231002.csv.zip  FR0000131104      Pending     None
12  XPAR_SHARES_F1_20231002.csv.zip  FR0000133308      Pending     None
13  XPAR_SHARES_F1_20231002.csv.zip  FR0010208488      Pending     None
14  XPAR_SHARES_F1_20231002.csv.zip  FR0010220475      Pending     None
15  XPAR_SHARES_F1_20231002.csv.zip  FR0010307819      Pending     None
16  XPAR_SHARES_F1_20231002.csv.zip  FR0013326246      Pending     None
17  XPAR_SHARES_F1_20231002.csv.zip  FR0014000MR3      Pending     None
18  XPAR_SHARES_F1_20231002.csv.zip  FR001400AJ45      Pending     None
19  XPAR_SHARES_F1_20231002.csv.zip  NL0000235190      Pending     None

In [16]:
def create_df():
    return pd.DataFrame(columns=['col1','col2'])

In [17]:
display(create_df())
create_df().to_csv('test.csv', header=True)
display(pd.read_csv('test.csv', index_col=0))

Empty DataFrame
Columns: [col1, col2]
Index: []

Empty DataFrame
Columns: [col1, col2]
Index: []

In [18]:
display(pd.read_csv('test.csv', index_col=0))
with FileLock('test.csv.lock'):
    display(pd.read_csv('test.csv', index_col=0))

Empty DataFrame
Columns: [col1, col2]
Index: []

Empty DataFrame
Columns: [col1, col2]
Index: []

In [19]:
df = create_df()
display(df)

Empty DataFrame
Columns: [col1, col2]
Index: []

In [20]:
display(df.empty)

True

In [3]:
data = {
    'Colonne1': [1, 2, 3, np.nan, 5, np.nan, 7, 8, np.nan, 10],
    'Colonne2': [np.nan, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, np.nan, 9.5, 10.5],
    'Colonne3': [1.1, np.nan, 3.3, 4.4, np.nan, 6.6, 7.7, 8.8, 9.9, 10.0]
}

# Création du DataFrame
df = pd.DataFrame(data)

# Affichage du DataFrame
display(df)

   Colonne1  Colonne2  Colonne3
0       1.0       NaN       1.1
1       2.0       2.5       NaN
2       3.0       3.5       3.3
3       NaN       4.5       4.4
4       5.0       5.5       NaN
5       NaN       6.5       6.6
6       7.0       7.5       7.7
7       8.0       NaN       8.8
8       NaN       9.5       9.9
9      10.0      10.5      10.0

In [6]:
display(df[~df['Colonne3'].isna()])

   Colonne1  Colonne2  Colonne3
0       1.0       NaN       1.1
2       3.0       3.5       3.3
3       NaN       4.5       4.4
5       NaN       6.5       6.6
6       7.0       7.5       7.7
7       8.0       NaN       8.8
8       NaN       9.5       9.9
9      10.0      10.5      10.0