In [74]:
import os, sys
import pandas as pd
import zipfile
from fastparquet import write

cwd = os.getcwd()

raw_path = os.path.join(os.path.dirname(cwd), 'data', 'raw', 'FOB')
processed_path = os.path.join(os.path.dirname(cwd), 'data', 'processed', 'FOB')

display(os.listdir(processed_path))

['FR0000045072_20231002.parquet.gzip',
 'FR0000120073_20231024_tmp.parquet',
 'FR0014000MR3_20231017_tmp.csv',
 'FR0014000MR3_20231017_tmp.parquet.gzip',
 'FR001400AJ45_20231031.csv.zip',
 'FR001400AJ45_20231031.parquet',
 'FR001400AJ45_20231031.parquet.gzip',
 'ReadMe',
 'test']

In [11]:
df = df.astype({col: 'str' for col in df.select_dtypes(include=['object']).columns})
display(df.dtypes)

cvalbdm               int64
isin                 object
mic                  object
cidgrc               object
event_date           object
event_time_utc       object
event_time_cet       object
sequence_number       int64
event_id              int64
order_id              int64
order_event_type     object
order_side           object
order_price         float64
order_size          float64
order_type           object
time_in_force        object
execution_id          int64
trade_size          float64
trade_price         float64
dtype: object

In [75]:
df = pd.read_parquet(os.path.join(processed_path, 'FR001400AJ45_20231031.parquet.gzip'))
display(df)

                               price      size  side
2023-10-31 03:01:47.151365898   8.60     465.0   Buy
2023-10-31 03:01:47.151365898  13.45       8.0   Buy
2023-10-31 03:01:47.151365898  15.00      15.0   Buy
2023-10-31 03:01:47.151365898  16.26      62.0   Buy
2023-10-31 03:01:47.151365898  17.00     200.0   Buy
...                              ...       ...   ...
2023-10-31 17:47:27.843038275  37.85 -329335.0  Sell
2023-10-31 17:47:27.843038275  37.96 -329335.0  Sell
2023-10-31 17:47:27.843038275  38.00 -329335.0  Sell
2023-10-31 17:47:27.843038275  39.95 -329335.0  Sell
2023-10-31 17:47:27.843038275  41.25 -329335.0  Sell

[5172651 rows x 3 columns]

In [86]:
a = df.loc[(df.index == df.index[2]) & (df['price'] == 15.00), 'price']
display(a, type(a), a.values)
display(df[df['price'] == 15.00])
display(df.loc[df['price'] == 15.00, :].index.unique())

2023-10-31 03:01:47.151365898    15.0
Name: price, dtype: float64

pandas.core.series.Series

array([15.])

                               price     size side
2023-10-31 03:01:47.151365898   15.0     15.0  Buy
2023-10-31 07:30:00.027735265   15.0     15.0  Buy
2023-10-31 07:30:00.281111106   15.0     15.0  Buy
2023-10-31 07:30:03.043495666   15.0     15.0  Buy
2023-10-31 07:30:03.043557367   15.0     55.0  Buy
...                              ...      ...  ...
2023-10-31 07:44:01.150799313   15.0  38456.0  Buy
2023-10-31 07:45:24.668308699   15.0  38456.0  Buy
2023-10-31 07:45:26.994690904   15.0  38456.0  Buy
2023-10-31 07:45:30.817591686   15.0  38456.0  Buy
2023-10-31 07:45:32.207950499   15.0  38456.0  Buy

[252 rows x 3 columns]

Index(['2023-10-31 03:01:47.151365898', '2023-10-31 07:30:00.027735265',
       '2023-10-31 07:30:00.281111106', '2023-10-31 07:30:03.043495666',
       '2023-10-31 07:30:03.043557367', '2023-10-31 07:30:03.043562056',
       '2023-10-31 07:30:03.043566154', '2023-10-31 07:30:03.043576753',
       '2023-10-31 07:30:03.043579739', '2023-10-31 07:30:03.043625001',
       ...
       '2023-10-31 07:40:03.961794217', '2023-10-31 07:42:47.867913112',
       '2023-10-31 07:42:50.637471029', '2023-10-31 07:42:52.024351356',
       '2023-10-31 07:42:53.108798891', '2023-10-31 07:44:01.150799313',
       '2023-10-31 07:45:24.668308699', '2023-10-31 07:45:26.994690904',
       '2023-10-31 07:45:30.817591686', '2023-10-31 07:45:32.207950499'],
      dtype='object', length=252)

In [73]:
display(test.loc[test['price'] == 74.83, :])

                               price  size side
2023-10-24 03:01:04.078950298  74.83  10.0  Buy