In [11]:
import os, sys
import pandas as pd
import zipfile
from fastparquet import write

cwd = os.getcwd()

raw_path = os.path.join(os.path.dirname(cwd), 'data', 'raw', 'FOB')

display(os.listdir(raw_path))

['ReadMe', 'XPAR_SHARES_F1_20231002.csv', 'XPAR_SHARES_F1_20231002.csv.zip']

In [3]:
df = pd.read_csv(os.path.join(raw_path, 'XPAR_SHARES_F1_20231002.csv'))
display(df)

<ipython-input-3-0d0afe37d2c9>:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(raw_path, 'XPAR_SHARES_F1_20231002.csv'))

,cvalbdm,isin,mic,cidgrc,event_date,event_time_utc,event_time_cet,sequence_number,event_id,order_id,order_event_type,order_side,order_price,order_size,order_type,time_in_force,execution_id,trade_size,trade_price
0,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886408,363384194933456904,16862367,Reload,Sell,16.50,500.0,Limit,0,0,0.0,0.0
1,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886409,363384194933456904,50416806,Reload,Sell,12.80,40.0,Limit,0,0,0.0,0.0
2,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886410,363384194933456904,67193907,Reload,Buy,7.13,100.0,Limit,0,0,0.0,0.0
3,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886411,363384194933456904,83971245,Reload,Buy,11.34,300.0,Limit,0,0,0.0,0.0
4,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886413,363384194933456904,100748461,Reload,Buy,11.34,500.0,Limit,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14398067,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090926,436004738924807190,17163177136,Cancel,Buy,75.00,0.0,Limit,0,0,0.0,0.0
14398068,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090927,436004738924807190,4076948656,Cancel,Buy,69.69,0.0,Limit,0,0,0.0,0.0
14398069,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090928,436004738924807190,3724627120,Cancel,Buy,65.01,0.0,Limit,0,0,0.0,0.0
14398070,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090929,436004738924807190,17028959408,Cancel,Buy,63.50,0.0,Limit,0,0,0.0,0.0
14398071,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090930,436004738924807190,4429270192,Cancel,Buy,51.25,0.0,Limit,0,0,0.0,0.0

In [11]:
df = df.astype({col: 'str' for col in df.select_dtypes(include=['object']).columns})
display(df.dtypes)

df.to_parquet('df.parquet.gzip', compression='gzip')

cvalbdm               int64
isin                 object
mic                  object
cidgrc               object
event_date           object
event_time_utc       object
event_time_cet       object
sequence_number       int64
event_id              int64
order_id              int64
order_event_type     object
order_side           object
order_price         float64
order_size          float64
order_type           object
time_in_force        object
execution_id          int64
trade_size          float64
trade_price         float64
dtype: object

In [12]:
df.to_parquet('df.parquet')

In [15]:
for i in [os.path.join(raw_path, 'XPAR_SHARES_F1_20231002.csv'), 
          os.path.join(raw_path, 'XPAR_SHARES_F1_20231002.csv.zip'), 
          'df.parquet', 
          'df.parquet.gzip']:
    
    file_size = os.path.getsize(i)
    file_size = file_size / (1024 * 1024)

    print(f"Taille du fichier {i} : {file_size:.2f} Mo")

Taille du fichier C:\Users\Utilisateur\Desktop\doctorat\2. Recherche\Article 2b\3. Python\PhD_article_2\data\raw\FOB\XPAR_SHARES_F1_20231002.csv : 2154.43 Mo
Taille du fichier C:\Users\Utilisateur\Desktop\doctorat\2. Recherche\Article 2b\3. Python\PhD_article_2\data\raw\FOB\XPAR_SHARES_F1_20231002.csv.zip : 318.83 Mo
Taille du fichier df.parquet : 463.41 Mo
Taille du fichier df.parquet.gzip : 262.04 Mo

In [16]:
DF = pd.read_parquet('df.parquet.gzip')
display(DF)

,cvalbdm,isin,mic,cidgrc,event_date,event_time_utc,event_time_cet,sequence_number,event_id,order_id,order_event_type,order_side,order_price,order_size,order_type,time_in_force,execution_id,trade_size,trade_price
0,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886408,363384194933456904,16862367,Reload,Sell,16.50,500.0,Limit,0,0,0.0,0.0
1,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886409,363384194933456904,50416806,Reload,Sell,12.80,40.0,Limit,0,0,0.0,0.0
2,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886410,363384194933456904,67193907,Reload,Buy,7.13,100.0,Limit,0,0,0.0,0.0
3,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886411,363384194933456904,83971245,Reload,Buy,11.34,300.0,Limit,0,0,0.0,0.0
4,72275,FR0000045072,XPAR,F1,2023-10-02,01:01:12.559510032,03:01:12.559510032,1015886413,363384194933456904,100748461,Reload,Buy,11.34,500.0,Limit,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14398067,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090926,436004738924807190,17163177136,Cancel,Buy,75.00,0.0,Limit,0,0,0.0,0.0
14398068,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090927,436004738924807190,4076948656,Cancel,Buy,69.69,0.0,Limit,0,0,0.0,0.0
14398069,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090928,436004738924807190,3724627120,Cancel,Buy,65.01,0.0,Limit,0,0,0.0,0.0
14398070,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090929,436004738924807190,17028959408,Cancel,Buy,63.50,0.0,Limit,0,0,0.0,0.0
14398071,49388,NL0000235190,XPAR,F1,2023-10-02,15:40:00.006035783,17:40:00.006035783,751090930,436004738924807190,4429270192,Cancel,Buy,51.25,0.0,Limit,0,0,0.0,0.0

In [3]:
proc_path = os.path.join(os.path.dirname(cwd), 'data', 'processed', 'FOB')
display(os.listdir(proc_path))

['FR0014000MR3_20231017_tmp.csv', 'FR001400AJ45_20231031.csv.zip', 'ReadMe']

In [9]:
df = pd.read_csv(os.path.join(proc_path, 'FR0014000MR3_20231017_tmp.csv'), index_col=1)
df.to_parquet(os.path.join(proc_path, 'FR0014000MR3_20231017_tmp.parquet.gzip'), compression='gzip')

In [28]:
with zipfile.ZipFile(os.path.join(proc_path, 'FR001400AJ45_20231031.csv.zip'), "r") as zip_file:
    
    with zip_file.open(zip_file.namelist()[0]) as csv_file:
        df = pd.read_csv(csv_file, index_col=0)

In [29]:
df.to_parquet(os.path.join(proc_path, 'FR001400AJ45_20231031.parquet'))

In [27]:
import pandas as pd
from fastparquet import write, ParquetFile

# Étape 1 : Création du fichier Parquet initial compressé
# Créer un DataFrame initial
df_initial = pd.DataFrame({
    'Colonne1': [1, 2, 3],
    'Colonne2': ['A', 'B', 'C']
})

# Écrire le DataFrame initial dans un fichier Parquet compressé avec gzip
write('mon_fichier_compressé.parquet', df_initial, compression='GZIP')

# Étape 2 : Ajout de nouvelles données au fichier Parquet compressé
# Créer un nouveau DataFrame avec des données supplémentaires
nouveau_df = pd.DataFrame({
    'Colonne1': [4, 5, 6],
    'Colonne2': ['D', 'E', 'F']
})

# Ajouter les nouvelles données au fichier Parquet compressé en conservant la compression
write('mon_fichier_compressé.parquet', nouveau_df, append=True, compression='GZIP')

# Vérification : Lire le fichier Parquet pour confirmer l'ajout
parquet_file = ParquetFile('mon_fichier_compressé.parquet')
df_complet = parquet_file.to_pandas()
print(df_complet)

   Colonne1 Colonne2
0         1        A
1         2        B
2         3        C
3         4        D
4         5        E
5         6        F

In [25]:
df = pd.read_parquet('mon_fichier_compressé.parquet')

In [23]:
display(df)

   Colonne1 Colonne2
0         1        A
1         2        B
2         3        C
3         4        D
4         5        E
5         6        F

In [32]:
f = 'FR001400AJ45_20231031.csv.zip'
fn = f.split('.')[0] + '.parquet.gzip'
display(fn)

'FR001400AJ45_20231031.parquet.gzip'