In [66]:
import os, sys
import pandas as pd
import zipfile
from fastparquet import write

cwd = os.getcwd()

raw_path = os.path.join(os.path.dirname(cwd), 'data', 'raw', 'FOB')
processed_path = os.path.join(os.path.dirname(cwd), 'data', 'processed', 'FOB')

display(os.listdir(processed_path))

['FR0000045072_20231002.parquet.gzip',
 'FR0000120073_20231024_tmp.parquet',
 'FR0014000MR3_20231017_tmp.csv',
 'FR0014000MR3_20231017_tmp.parquet.gzip',
 'FR001400AJ45_20231031.csv.zip',
 'FR001400AJ45_20231031.parquet',
 'FR001400AJ45_20231031.parquet.gzip',
 'ReadMe',
 'test']

In [11]:
df = df.astype({col: 'str' for col in df.select_dtypes(include=['object']).columns})
display(df.dtypes)

cvalbdm               int64
isin                 object
mic                  object
cidgrc               object
event_date           object
event_time_utc       object
event_time_cet       object
sequence_number       int64
event_id              int64
order_id              int64
order_event_type     object
order_side           object
order_price         float64
order_size          float64
order_type           object
time_in_force        object
execution_id          int64
trade_size          float64
trade_price         float64
dtype: object

In [48]:
df = pd.read_parquet(os.path.join(processed_path, 'FR0000120073_20231024_tmp.parquet'))
display(df)

                                price   size  side
2023-10-24 03:01:04.078950298   74.83   10.0   Buy
2023-10-24 03:01:04.078950298   78.32   50.0   Buy
2023-10-24 03:01:04.078950298   80.00  110.0   Buy
2023-10-24 03:01:04.078950298   82.00    3.0   Buy
2023-10-24 03:01:04.078950298   86.00   58.0   Buy
...                               ...    ...   ...
2023-10-24 03:01:04.078950298  202.10   25.0  Sell
2023-10-24 03:01:04.078950298  205.60   49.0  Sell
2023-10-24 03:01:04.078950298  210.00   71.0  Sell
2023-10-24 03:01:04.078950298  215.30    3.0  Sell
2023-10-24 03:01:04.078950298  217.15   10.0  Sell

[693 rows x 3 columns]

In [60]:
display(df.columns)
test = df.copy()
display(test.reset_index())

Index(['price', 'size', 'side'], dtype='object')

                            index   price   size  side
0   2023-10-24 03:01:04.078950298   74.83   10.0   Buy
1   2023-10-24 03:01:04.078950298   78.32   50.0   Buy
2   2023-10-24 03:01:04.078950298   80.00  110.0   Buy
3   2023-10-24 03:01:04.078950298   82.00    3.0   Buy
4   2023-10-24 03:01:04.078950298   86.00   58.0   Buy
..                            ...     ...    ...   ...
688 2023-10-24 03:01:04.078950298  202.10   25.0  Sell
689 2023-10-24 03:01:04.078950298  205.60   49.0  Sell
690 2023-10-24 03:01:04.078950298  210.00   71.0  Sell
691 2023-10-24 03:01:04.078950298  215.30    3.0  Sell
692 2023-10-24 03:01:04.078950298  217.15   10.0  Sell

[693 rows x 4 columns]

In [55]:
write(os.path.join(processed_path, 'test'), test, append=False)
write(os.path.join(processed_path, 'test'), test, append=True)

In [59]:
DF = pd.read_parquet(os.path.join(processed_path, 'test'))
display(DF)

                                price   size  side
index
2023-10-24 03:01:04.078950298   74.83   10.0   Buy
2023-10-24 03:01:04.078950298   78.32   50.0   Buy
2023-10-24 03:01:04.078950298   80.00  110.0   Buy
2023-10-24 03:01:04.078950298   82.00    3.0   Buy
2023-10-24 03:01:04.078950298   86.00   58.0   Buy
...                               ...    ...   ...
2023-10-24 03:01:04.078950298  202.10   25.0  Sell
2023-10-24 03:01:04.078950298  205.60   49.0  Sell
2023-10-24 03:01:04.078950298  210.00   71.0  Sell
2023-10-24 03:01:04.078950298  215.30    3.0  Sell
2023-10-24 03:01:04.078950298  217.15   10.0  Sell

[2079 rows x 3 columns]

In [57]:
write(os.path.join(processed_path, 'test'), test, append=True)

In [64]:
display(DF.loc[(DF.index == DF.index[0]) & (DF['price'] == 78.32), :])

                               price  size side
index
2023-10-24 03:01:04.078950298  78.32  50.0  Buy
2023-10-24 03:01:04.078950298  78.32  50.0  Buy
2023-10-24 03:01:04.078950298  78.32  50.0  Buy

In [67]:
df = pd.read_parquet(os.path.join(processed_path, 'FR0000045072_20231002.parquet.gzip'))
display(df[df['size'] < 0])

                                price       size  side
2023-10-02 07:31:04.753129182  12.126    -1690.0  Sell
2023-10-02 07:31:04.753129182  12.230    -5472.0  Sell
2023-10-02 07:31:04.777487026  12.126    -1690.0  Sell
2023-10-02 07:31:04.777487026  12.230    -5472.0  Sell
2023-10-02 07:31:04.790853936  12.126    -1328.0  Sell
...                               ...        ...   ...
2023-10-02 17:50:00.417817476  15.500 -2339645.0  Sell
2023-10-02 17:50:00.417817476  16.666 -2348445.0  Sell
2023-10-02 17:50:00.417817476  16.750 -2334803.0  Sell
2023-10-02 17:50:00.417817476  16.892 -2341482.0  Sell
2023-10-02 17:50:00.417817476  18.088 -2348220.0  Sell

[12214140 rows x 3 columns]